mt:
- password: xxxxxx
  username: xxxxxxxx
paoluz:
- password: xxxxxxxxxx
  username: xxxxxxxx
pdawiki:
- password: xxxxxxxxxx
  username: xxxxxxxx
cloud189:
- password: xxxxxxxxxx
  username: xxxxxxxx

